default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tailwind_development
  username: root
  password: root
  host: localhost
  variables:
    sql_mode: TRADITIONAL